### ISSUE TITLE
Create a simple default React frontend

### ISSUE THREAD

**Issue by lxy009** [open-build/BabbleBeaver-#13]
I don't believe we have a working frontend for this.

**Comment by lxy009** [comment]
This should probably be a separate repo

**Comment by glind** [comment]
Yes the FE should be separate.


build it quickly
Cloud Native Product and Release Management
Greg Lind
CEO - Founder, buildly.io
510-633-3469 | ***@***.***
https://buildly.io
calendly: http://calendly.com/buildly-greg
